language: python

sudo: false
cache:
  - $HOME/download # Sufficient to add miniconda.sh to TRAVIS cache.
  - $HOME/miniconda
  - $HOME/.cache/pip

notifications:
  email: false

stages:
  - docs
  - lint check
  - static check
  - test

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytorch -c pytorch
  - source activate test-environment
  # Install current torchgeometry
  - python setup.py install

after_success:
  - codecov


jobs:
  include:
    - stage: lint check
      python: "3.6"
      before_install: # Nothing to do
      install:
        - pip install flake8
      script: python scripts/verify.py --check lint

    - stage: static check
      python: "3.6"
      install:
        - pip install mypy mypy-extensions
      script: python scripts/verify.py --check mypy

    - stage: test
      python: "3.6"
      install:
        - pip install -U pytest codecov
      script: pytest test

    - stage: docs
      python: "3.6"
      install:
        - conda install -y --file docs/requirements.txt -c conda-forge 
      script:
        - python scripts/verify.py --check build-docs
      after_success: # Nothing to do
