language: python

sudo: true

notifications:
  email: false

matrix:
  include:
    - env: MYPY_TYPE_CHECK
      python: "3.6"
      install: pip install mypy mypy-extensions 
      script: mypy @mypy_files.txt --ignore-missing-imports

stages:
  - lint check
  - test
  - docs

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytorch scipy -c pytorch
  - source activate test-environment
  - python setup.py install

install:
  - pip install --upgrade pytest
  - pip install codecov

after_success:
  - codecov


jobs:
  include:
    - stage: lint check
      python: "3.6"
      before_install: # Nothing to do
      install: pip install flake8
      script: python scripts/verify.py --check lint

    - env: static check
      python: "3.6"
      install: pip install mypy mypy-extensions 
      script: mypy @mypy_files.txt --ignore-missing-imports

    - stage: test
      python: "3.6"
      script: pytest test

    - stage: docs
      python: "3.6"
      install:
        - pip install -r docs/requirements.txt
      script:
        - python scripts/verify.py --check build-docs
        # Create .nojekyll file to serve correctly _static and friends
        - touch build/html/.nojekyll
      after_success: # Nothing to do
